import type { Metadata } from "next";
import { Nav } from "@/components/nav";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="pb-16 overflow-y-scroll h-[calc(100vh_-_80px)]">
          {children}
        </div>
        <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200">
          <Nav />
        </div>
      </body>
    </html>
  );
}
